# Generated by Django 5.2.7 on 2025-12-28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BazaarPricePoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.CharField(db_index=True, max_length=128)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("buy_price", models.FloatField()),
                ("sell_price", models.FloatField()),
                ("buy_volume", models.FloatField(default=0.0)),
                ("sell_volume", models.FloatField(default=0.0)),
                ("buy_orders", models.IntegerField(default=0)),
                ("sell_orders", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["product_id", "recorded_at"], name="api_bazaarp_product_fce7f4_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="bazaarpricepoint",
            constraint=models.UniqueConstraint(fields=("product_id", "recorded_at"), name="uniq_bazaar_point"),
        ),
    ]
